import Reservoir
import numpy as np

wanted = 50
inputM = np.array([[1]])
outputM = np.array([[50]])
outputM = outputM.reshape(1,1)
output = 0

res = Reservoir.Reservoir(1, 50, 1)
res.train(outputM, initTime=0)
output = res.getVals(inputM)
outputM = np.append(outputM, [[50]])
outputM = outputM.reshape(-1, 1)
print("input: ", inputM)
print("output: ", output[0][0])
while (output[0][0] > (wanted * 1.05)) | (output[0][0] < (wanted * .95)):
    res.train(outputM)
    output = res.getVals(inputM)
    outputM = np.append(outputM, [[50]])
    outputM = outputM.reshape(-1, 1)
    print("input: ", inputM)
    print("output: ", output[0][0])

output = res.getVals(inputM + .001)
print("input: ", inputM+ .001)
print("output: ", output[0][0])
output = res.getVals(inputM + .01)
print("input: ", inputM+ .01)
print("output: ", output[0][0])
output = res.getVals(inputM + .1)
print("input: ", inputM + .1)
print("output: ", output[0][0])
output = res.getVals(inputM + 1)
print("input: ", inputM + 1)
print("output: ", output[0][0])
output = res.getVals(inputM - .001)
print("input: ", inputM - .001)
print("output: ", output[0][0])
output = res.getVals(inputM - .01)
print("input: ", inputM - .01)
print("output: ", output[0][0])
output = res.getVals(inputM - .1)
print("input: ", inputM - .1)
print("output: ", output[0][0])
output = res.getVals(inputM - 1)
print("input: ", inputM - 1)
print("output: ", output[0][0])